OOP school library: add basic UI : module 4
yusufyusie/School-Library pull request #4
Opened 2023-10-20 12:41 UTC by yusufyusie

# Project requirements
- Created a `app.rb` file that will serve as your console app entry-point. It should have methods that do the following:
  - List all books.
  - List all people.
  - Create a person (teacher or student, not a plain `Person`).
  - Create a book.
  - Create a rental.
  - List all rentals for a given person id.
- In your `main.rb` define the entry point, this will be a method called `main` that is invoked at the end of your file. This method should do the following:
  - Present the user with a list of options to perform.
  - Lets users choose an option.
  - If needed, ask for parameters for the option.
  - Have a way to quit the app.

2023-10-20 13:30 UTC, ShadyShawkat requested changes
## Hi @yusufyusie, 

Good job so far! 👍🏻 
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight
- Correct use of GitFlow ✔️ 
- Descriptive commit messages ✔️ 
- Professional looking pull request ✔️ 

![Image](https://media.giphy.com/media/UdaSUYClr92cjWpeVx/giphy.gif)

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-20 13:30 UTC, ShadyShawkat commented on person.rb
>    end
- [ ] Please fix the following error that occurs whenever the user tries to create a student.

![image](https://github.com/yusufyusie/School-Library/assets/62290545/bb408dd5-b9df-45e8-b86b-b7045420bcc2)

- [ ] A similar error appears when creating a teacher. Kindly fix that as well.

![image](https://github.com/yusufyusie/School-Library/assets/62290545/77ebdbc6-6653-4b25-bd1c-fa112f824e6b)

2023-10-20 13:30 UTC, ShadyShawkat commented on rental.rb
> +end
- [ ] I couldn't test adding and displaying rentals due to the other errors. Kindly make sure it works as intended.

2023-10-21 06:02 UTC, Munsa1 approved these changes
Hi @yusufyusie, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
App Works As Expected :heavy_check_mark: 
Correct Git Flow :heavy_check_mark: 


## Optional suggestions
N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-10-21 14:59 UTC, merged